services:
  jupyter:
    build: .
    image: jupyternotebook:latest
    ports:
      - "${APP_PORT:-8888}:8888"
    volumes:
      - "${NOTEBOOK_FOLDER:-./../../notebooks}:/home/jovyan/work"
      - "${DATASET_FOLDER:-./../../datasets}:/home/jovyan/datasets"
